---
name: test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn run lint
    - run: yarn test
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        GITHUB_OWNER: ${{ github.repository_owner }}
        GITHUB_REPO: ${{ github.event.repository.name }}

  upload:
    runs-on: ubuntu-latest
    steps:
    - run: |
        mkdir -p uploads/dir1/dir2
        echo ${GITHUB_SHA}
        echo ${GITHUB_SHA} > uploads/sha1
        echo ${GITHUB_SHA} > uploads/dir1/dir2/sha2
    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: uploads

  test:
    needs: upload
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        name: artifact
        path: downloads
    - run: |
        ls -lR downloads
        cat downloads/sha1
        cat downloads/dir1/dir2/sha2
        echo "$(cat downloads/sha1) == ${GITHUB_SHA}"
        # FIXIT: Githab API returns an outdated list of repository artifacts
        # [[ $(cat downloads/sha1) == ${GITHUB_SHA} ]]
